### ISSUE TITLE
Annotations seem not work properly on non-struct types.

### ISSUE THREAD

**Issue by sslime336** [galkowskit/go-interface-annotations#4]
Firstly, I'd like to say that was awesome! 

![图片](https://user-images.githubusercontent.com/97684920/189558851-e69c22e3-4b10-4bd6-9bbf-c7158912e981.png)

In Go, not only struct types can achieve different interfaces, other like string, int, ... primitive type, user defined types which can carry methods can also work with that.

Anyway, this is a delightful extension ! 😃

**Comment by galkowskit** [comment]
What would be the use case for that? Where would you want the `type Alice string` to link to? 🤔

**Comment by sslime336** [comment]
I am sorry for that inappropriate example, below is a heap impl the interface from "container/heap"

**Comment by galkowskit** [comment]
Ah, makes sense. So in the first example even though the `Alice` is a `string` and not a struct, we'd still want it to point to `Person` because it implements the interface. I haven't used VS Code for a moment, since changing jobs I migrated to GoLand/nvim.

But I'll see what I can do, I need to check what the LSP provides. :)

**Comment by galkowskit** [comment]
Sorry it took so long, mostly because I didn't use VS Code. But this got fixed in the newest release. Unfortunately, I can't push the update to Extension store, because... I lost my Microsoft access (changing countries and phone numbers). I'll get it back on 6th of February and I'll push the update then. Until then you can always grab the extension from GitHub.

**Comment by galkowskit** [comment]
https://marketplace.visualstudio.com/items?itemName=galkowskit.go-interface-annotations <- released now. :)
